[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies.godot-wasm-bindgen]
path = "../.."
version = "=0.1.0"
